//
//  MainCollectionViewCellProperty.swift
//  CardDiary_220221
//
//  Created by 윤대식 on 2022/04/27.
//

import Foundation
import UIKit

struct MainCollectionViewCellProperty {
  let monthNumber: Int
  let monthText: String
  var backgroundColor: UIColor
  var calendar: HistoryCellProperty
}

struct HistoryCellProperty {
  let dayNumber: [Int]
  let daytext: [String]
  var textField: String
}

var cellProperties: [MainCollectionViewCellProperty] = [
  MainCollectionViewCellProperty(monthNumber: 1, monthText: "Jan", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30,31],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 2, monthText: "Feb", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 3, monthText: "Mar", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30,31],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 4, monthText: "Apr", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 5, monthText: "May", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30,31],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 6, monthText: "Jun", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 7, monthText: "Jul", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30, 31],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 8, monthText: "Aug", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30,31],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 9, monthText: "Sep", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30 ],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 10, monthText: "Oct", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30,31],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 11, monthText: "Nov", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE"],
                                                               textField: "")),
  MainCollectionViewCellProperty(monthNumber: 12, monthText: "Dec", backgroundColor: .white,
                                 calendar: HistoryCellProperty(dayNumber: [1,2,3,4,5,6,7,8,9,10,
                                                                           11,12,13,14,15,16,17,18,19,20,
                                                                           21,22,23,24,25,26,27,28,29,30,31],
                                                               daytext: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                                                                         "MON", "TUE", "WED"],
                                                               textField: ""))
]
